/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_JNITest */

#ifndef _Included_com_jni_JNITest
#define _Included_com_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_JNITest
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_JNITest_logTest
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
