/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

#include "com_jni_JNITest.h"

JNIEXPORT void JNICALL Java_com_jni_JNITest_logTest(JNIEnv *env, jobject thisObj) {

	__android_log_print(ANDROID_LOG_INFO, "JNITest", "Java_com_jni_JNITest_logTest.............1");

}
